#!/bin/bash

echo "=== 纪念堂标题更新验证 ==="

# 1. 检查当前媒体文件数量
echo "1. 检查当前媒体文件数量..."
FILE_COUNT=$(curl -s "http://localhost:5000/api/memorial/list" | jq '.data | length')
echo "当前媒体文件数量: $FILE_COUNT"

echo -e "\n=== 纪念堂标题更新完成 ==="
echo "新增内容："
echo ""
echo "1. 标题结构："
echo "   - 主标题：🏛️ 纪念堂"
echo "   - 副标题：我们的爱，埋藏于此"
echo ""
echo "2. 副标题样式："
echo "   - 字体大小：移动端12px，桌面端14px"
echo "   - 颜色：rgba(255, 255, 255, 0.8) 半透明白色"
echo "   - 字体样式：italic 斜体"
echo "   - 对齐方式：center 居中"
echo "   - 阴影效果：textShadow: '0 1px 5px rgba(0, 0, 0, 0.5)'"
echo ""
echo "3. 布局调整："
echo "   - 上边距：margin: '4px 0 0 0'"
echo "   - 与主标题保持适当间距"
echo "   - 整体居中对齐"
echo ""
echo "4. 视觉效果："
echo "   - 主标题：粗体，较大字体"
echo "   - 副标题：斜体，较小字体，半透明"
echo "   - 层次分明，富有诗意"
echo ""
echo "5. 响应式设计："
echo "   - 移动端和桌面端字体大小自适应"
echo "   - 保持在不同设备上的可读性"
echo ""
echo "现在纪念堂标题更加富有情感和诗意！"
echo "有 $FILE_COUNT 个媒体文件可供测试。"
