#!/bin/bash

# 测试纪念堂功能
echo "🏛️ 测试纪念堂功能"
echo "================================"

API_BASE="http://localhost:5000/api"

echo "1. 设置废墟状态为true..."
curl -s -X POST "${API_BASE}/star-city/admin/set-ruins" \
  -H "Content-Type: application/json" \
  -d '{"isRuins": true}' | jq '.' || echo "设置废墟状态失败"

echo -e "\n2. 获取星星城信息（确认废墟状态）..."
curl -s "${API_BASE}/star-city/info" | jq '.data | {level, isRuins, weather}' || echo "获取星星城信息失败"

echo -e "\n🏛️ 纪念堂功能测试完成！"
echo ""
echo "前端测试步骤："
echo "1. 打开星星城页面"
echo "2. 确认当前处于废墟状态（等级0，废墟背景，废墟标题）"
echo "3. 查看星星城中心区域是否显示两个白圈："
echo "   - 纪念碑白圈（位置：23%, 48%）"
echo "   - 纪念堂白圈（位置：23%, 58%）"
echo "4. 点击纪念堂白圈"
echo "5. 应该弹出纪念堂页面，包含："
echo "   - 纪念堂标题（🏛️ 纪念堂）"
echo "   - 关闭按钮（右上角X）"
echo "   - 媒体展示区域（平铺网格布局）"
echo "   - 上传按钮（带+号的空素材）"
echo "   - 每个素材右上角的删除按钮"
echo ""
echo "纪念堂功能特点："
echo "- 位置：纪念碑右侧（left: 58%）"
echo "- 样式：与纪念碑相同的白色波纹动画"
echo "- 动画：3.5秒脉冲动画（与纪念碑略有不同）"
echo "- 页面：全屏弹窗，深色主题"
echo "- 布局：平铺素材网格布局"
echo "- 上传：支持图片和视频格式，点击+号上传"
echo "- 删除：每个素材右上角有删除按钮"
echo "- 展示：图片和视频预览，文件名显示"
echo ""
echo "后续开发计划："
echo "1. 后端API：文件上传接口"
echo "2. 数据库：媒体文件存储表"
echo "3. 前端：文件上传和预览功能"
echo "4. 媒体播放：图片查看和视频播放"
echo ""
echo "测试完成后，可以运行以下命令恢复正常状态："
echo "curl -X POST ${API_BASE}/star-city/admin/set-ruins -H 'Content-Type: application/json' -d '{\"isRuins\": false}'"
