#!/bin/bash

echo "=== 纪念堂媒体全屏横屏功能验证 ==="

# 1. 检查当前媒体文件数量
echo "1. 检查当前媒体文件数量..."
FILE_COUNT=$(curl -s "http://localhost:5000/api/memorial/list" | jq '.data | length')
echo "当前媒体文件数量: $FILE_COUNT"

echo -e "\n=== 纪念堂媒体全屏横屏功能完成 ==="
echo "新增功能："
echo ""
echo "1. 强制横屏样式："
echo "   - 外层容器：rotate(90deg) 强制横屏"
echo "   - 尺寸调整：width: 100vh, height: 100vw"
echo "   - 最高层级：z-index: 100003"
echo ""
echo "2. 内容适配："
echo "   - 内层内容：transform: none 保持横屏方向"
echo "   - 最大尺寸：max-width: 90vh, max-height: 90vw"
echo "   - 居中对齐：flex 布局居中显示"
echo ""
echo "3. 按钮调整："
echo "   - 关闭按钮：保持圆形样式"
echo "   - 位置固定：top: -50px, right: 0"
echo "   - 半透明背景：rgba(255, 255, 255, 0.2)"
echo ""
echo "4. 媒体内容："
echo "   - 图片/视频：max-width/max-height: 100%"
echo "   - 圆角边框：border-radius: 10px"
echo "   - 保持比例：object-fit: contain"
echo ""
echo "5. 与星星城一致："
echo "   - 相同的横屏旋转逻辑"
echo "   - 相同的尺寸计算方式"
echo "   - 相同的层级管理"
echo ""
echo "现在纪念堂媒体全屏显示与星星城保持一致的横屏体验！"
echo "有 $FILE_COUNT 个媒体文件可供测试全屏横屏效果。"
