#!/bin/bash

echo "===================="
echo "管理后台前端界面测试指南"
echo "===================="
echo ""

SERVER_URL="http://localhost:5000"

echo "🚀 测试步骤："
echo ""

echo "1. 启动后端服务："
echo "   cd eden-server && npm start"
echo ""

echo "2. 在浏览器中打开管理界面："
echo "   http://localhost:5000/admin.html"
echo ""

echo "3. 管理员登录信息："
echo "   用户名: admin"
echo "   密码: admin2008"
echo ""

echo "4. 测试功能验证："
echo "   ✅ 登录成功后应该看到管理控制面板"
echo "   ✅ 点击'居所事件'标签页"
echo "   ✅ 点击'🔄 刷新概览'按钮查看各居所事件历史统计"
echo "   ✅ 选择一个居所，点击'🗑️ 清除历史'按钮"
echo "   ✅ 确认对话框应该显示警告信息"
echo "   ✅ 清除后刷新概览，对应居所的记录数应该变为0"
echo ""

echo "5. 界面功能说明："
echo "   📊 居所事件历史概览："
echo "      - 显示所有居所的事件历史记录数量"
echo "      - 卡片式布局，响应式设计"
echo "      - 实时数据更新"
echo ""
echo "   🗑️ 清除居所事件历史："
echo "      - 下拉选择要清除的居所"
echo "      - 确认对话框防止误操作"
echo "      - 操作成功后自动刷新概览"
echo "      - 完整的错误处理和用户反馈"
echo ""

echo "6. API接口测试（可选）："
echo "   # 获取管理员Token"
echo "   TOKEN=\$(curl -s -X POST \"${SERVER_URL}/api/admin/login\" \\"
echo "     -H \"Content-Type: application/json\" \\"
echo "     -d '{\"username\": \"admin\", \"password\": \"admin2008\"}' | jq -r '.data.token')"
echo ""
echo "   # 获取居所事件历史概览"
echo "   curl -X GET \"${SERVER_URL}/api/admin/residence-event-history/overview\" \\"
echo "     -H \"Authorization: Bearer \$TOKEN\" | jq '.'"
echo ""
echo "   # 清除城堡事件历史"
echo "   curl -X DELETE \"${SERVER_URL}/api/admin/residence-event-history/castle\" \\"
echo "     -H \"Authorization: Bearer \$TOKEN\" | jq '.'"
echo ""

echo "===================="
echo "预期结果："
echo "- 管理界面应该正常显示居所事件管理功能"
echo "- 概览数据应该正确加载和显示"
echo "- 清除功能应该正常工作并提供用户反馈"
echo "- 所有操作都应该有适当的错误处理"
echo "===================="
